// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaAdopcionMascotas.Models;

#nullable disable

namespace SistemaAdopcionMascotas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250502162323_UpdateEntities")]
    partial class UpdateEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaAdopcionMascotas.Models.Adopcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdoptanteId")
                        .HasColumnType("integer");

                    b.Property<int>("MascotaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdoptanteId");

                    b.HasIndex("MascotaId")
                        .IsUnique();

                    b.ToTable("Adopciones");
                });

            modelBuilder.Entity("SistemaAdopcionMascotas.Models.Adoptante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Adoptantes");
                });

            modelBuilder.Entity("SistemaAdopcionMascotas.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoAdopcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("SistemaAdopcionMascotas.Models.Adopcion", b =>
                {
                    b.HasOne("SistemaAdopcionMascotas.Models.Adoptante", "Adoptante")
                        .WithMany("Adopciones")
                        .HasForeignKey("AdoptanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAdopcionMascotas.Models.Mascota", "Mascota")
                        .WithOne("Adopcion")
                        .HasForeignKey("SistemaAdopcionMascotas.Models.Adopcion", "MascotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adoptante");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("SistemaAdopcionMascotas.Models.Adoptante", b =>
                {
                    b.Navigation("Adopciones");
                });

            modelBuilder.Entity("SistemaAdopcionMascotas.Models.Mascota", b =>
                {
                    b.Navigation("Adopcion");
                });
#pragma warning restore 612, 618
        }
    }
}
